server:
  undertow:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
    io-threads: 10
    worker-threads: 100
  port: 8080
  mvc:
    async:
      request-timeout: -1

spring:
  data:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
      open-in-view: true
      show-sql: true
      database-platform: h2
  datasource:
    url: jdbc:h2:mem:zooplus
    name: zooplus
    username: zooplus
    password: 852147
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

endpoints:
  flyway:
    web:
      enabled: true

feign:
  currency:
    name: openexchangerates
    url: https://openexchangerates.org/api/latest.json

#------------------------ Spring security ----------------------------------#
security.basic.enabled: false # Security was disabled for this test